### ISSUE TITLE
[1.19 | Forge] Disc doesn't stop playing when removing it from the jukebox

### ISSUE THREAD

**Issue by Illios42** [williambl/portable-jukebox#5]
Heya, love this mod's idea as I use a lot of other mods that add discs, so thank you!

I've been trying out your mod with the rest of my modpack and it seems like the discs won't stop playing when I take them out of the jukebox. I am using v2.2.0 on Forge 41.0.110. Both vanilla and modded discs are affected and the music only stops if I fully turn down master volume once (turning down jukebox doesn't change anything for some reason). Hope you can fix this as I would love to include it!

**Comment by kenbaird13** [comment]
This is also present on fabric
